// real app that uses google gemini api to generate content and display it in a chat ui
// should be responsible and handle errors gracefully, santize user input, and provide feedback to the user when something goes wrong.
// use guardrails to prevent harmful or inappropriate content from being generated, and provide options for users to report any issues they encounter with the generated content.
// add disclaimer about the limitations of the model and the potential      for bias in the generated content, and encourage users to use the generated content responsibly and critically.
// create component named Responsible that includes all of the above features and can be used in the App component to display the chat interface with the google gemini api.

import React, { useState } from 'react'
import { generateContent } from './responsegoogle'
const Responsible = () => {
    const [messages, setMessages] = useState([])
    const [input, setInput] = useState('')
    const [error, setError] = useState(null)
    const handleSend = async () => {
        if (input.trim() === '') return
        const newMessages = [...messages, { role: 'user', content: input }]
        setMessages(newMessages)
        setInput('')
        
        try {
            const response = await generateContent(newMessages)
            
            // Handle the response object from generateContent
            if (response.success) {
                setMessages([...newMessages, { role: 'assistant', content: response.content }])
                setError(null)
            } else {
                // Handle guardrail or error responses
                setMessages([...newMessages, { role: 'assistant', content: response.error }])
                setError(response.isGuardrail ? 'Content filtered by guardrails' : response.error)
            }
        }
        catch (error) {
            setError(error.message || 'Error generating response')
        }
    }
    const handleReport = () => {
        // handle report logic here, such as sending the reported content to a server or displaying a thank you message to the user
        alert('Thank you for reporting this content. We will review it as soon as possible.')
    }
    return (
        <div style={{ maxWidth: '600px', margin: '0 auto', padding: '20px' }}>
            <h1>Chat with Gemini-3-Flash-Preview</h1>
            <div style={{ border: '1px solid #ccc', padding: '10px', height: '400px', overflowY: 'scroll' }}>

                {messages.map((msg, index) => (
                    <div key={index} style={{ marginBottom: '10px', textAlign: msg.role === 'user' ? 'right' : 'left' }}>
                        <div style={{ display: 'inline-block', padding: '10px', borderRadius: '10px', backgroundColor: msg.role === 'user' ? '#007bff' : '#f1f1f1', color: msg.role === 'user' ? '#fff' : '#000' }}>
                            {msg.content}
                            {msg.role === 'assistant' && (
                                <button onClick={handleReport} style={{ marginLeft: '10px', padding: '5px 10px', borderRadius: '5px', border: 'none', backgroundColor: '#dc3545', color: '#fff' }}>
                                    Report
                                </button>
                            )}
                        </div>
                    </div>
                ))}
            </div>
            <div style={{ marginTop: '10px', display: 'flex' }}>
                <input
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    style={{ flex: 1, padding: '10px', borderRadius: '5px', border: '1px solid #ccc' }}
                    placeholder="Type your message..."
                    onKeyPress={(e) => {
                        if (e.key === 'Enter') {
                            handleSend()
                        }
                    }}
                />
                <button onClick={handleSend} style={{ marginLeft: '10px', padding: '10px 20px', borderRadius: '5px', border: 'none', backgroundColor: '#007bff', color: '#fff' }}>
                    Send
                </button>
            </div>
            {error && <div style={{ marginTop: '10px', color: 'red' }}>{error}</div>}
            <div style={{ marginTop: '20px', fontSize: '12px', color: '#666' }}>
                <p><strong>Disclaimer:</strong> The responses generated by this model are based on patterns in the data it was trained on and may contain biases or inaccuracies. Please use the generated content responsibly and critically, and report any issues you encounter.</p>
            </div>
        </div>
    )
}
export default Responsible
